(() => {
  const current = document.currentScript;
  const next = current && current.nextElementSibling;
  if (next && next.tagName === 'SCRIPT' && /app\.js/.test(next.getAttribute('src') || '')) next.remove();

  document.documentElement.lang = 'zh-CN';
  document.title = 'PC 硬件采购仪表盘';
  const viewport = document.querySelector('meta[name="viewport"]');
  if (viewport) viewport.content = 'width=device-width,initial-scale=1,viewport-fit=cover';
  const themeMeta = document.querySelector('meta[name="theme-color"]') || document.head.appendChild(document.createElement('meta'));
  themeMeta.name = 'theme-color'; themeMeta.content = '#0f6fff';

  const css = `
  :root{color-scheme:light dark;--bg:#f3f6fa;--panel:#fff;--p2:#edf2f7;--text:#15202b;--muted:#687789;--border:#d9e1e9;--accent:#0f6fff;--soft:#e8f1ff;--good:#0c8b61;--warn:#a96500;--bad:#bd3b3b;--shadow:0 12px 30px rgba(24,43,68,.07);--nav:72px}
  [data-theme=dark]{--bg:#0c1118;--panel:#151c25;--p2:#202a35;--text:#eff5fb;--muted:#9cabbc;--border:#303b48;--accent:#6aafff;--soft:#162d48;--good:#55d8a6;--warn:#f0b458;--bad:#ff8b8b;--shadow:none}
  *{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:var(--bg);color:var(--text);font-family:-apple-system,BlinkMacSystemFont,"SF Pro Text","PingFang SC","Microsoft YaHei",sans-serif;-webkit-font-smoothing:antialiased}button,input,select{font:inherit}a{color:var(--accent)}
  .app{width:min(1280px,calc(100% - 32px));margin:auto;padding:28px 0 64px}.top{display:flex;justify-content:space-between;gap:20px;margin-bottom:22px}.eye,.kick{margin:0 0 7px;color:var(--accent);font-weight:750;letter-spacing:.06em;font-size:.74rem}.top h1{margin:0;font-size:clamp(1.65rem,4vw,2.6rem)}.subhead{margin:10px 0 0;color:var(--muted)}
  .actions{display:flex;gap:8px;flex-wrap:wrap;justify-content:flex-end}button,.file{min-height:42px;border:1px solid var(--border);background:var(--panel);color:var(--text);border-radius:11px;padding:9px 13px;cursor:pointer}.file input{display:none}
  .metrics{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px;margin-bottom:18px}.metric,.panel{background:var(--panel);border:1px solid var(--border);border-radius:16px;box-shadow:var(--shadow)}.metric{padding:16px}.metric .label{color:var(--muted);font-size:.84rem}.metric .value{font-size:1.45rem;font-weight:780;margin-top:6px}.hint,.small{color:var(--muted);font-size:.78rem;margin-top:5px}
  .grid{display:grid;grid-template-columns:minmax(0,2fr) minmax(300px,1fr);gap:16px;align-items:start}.panel{padding:18px;margin-bottom:16px}.head{display:flex;justify-content:space-between;align-items:flex-start;gap:12px;margin-bottom:14px}.head h2,.panel h2{margin:0;font-size:1.08rem}.controls{display:grid;grid-template-columns:minmax(170px,1.45fr) repeat(3,minmax(115px,.7fr));gap:10px;margin-bottom:14px}.control{color:var(--muted);font-size:.8rem}.control input,.control select{width:100%;min-height:42px;margin-top:5px;border:1px solid var(--border);background:var(--p2);color:var(--text);border-radius:10px;padding:9px 10px}
  .table{overflow:auto;border:1px solid var(--border);border-radius:13px}table{border-collapse:collapse;width:100%;min-width:900px}th,td{padding:12px;border-bottom:1px solid var(--border);text-align:left;vertical-align:top;font-size:.88rem}th{color:var(--muted);background:var(--p2)}.model{font-weight:720}.pill{display:inline-flex;border-radius:999px;padding:4px 8px;font-size:.72rem;background:var(--p2);margin:2px 4px 2px 0}.good{color:var(--good)}.warn{color:var(--warn)}.bad{color:var(--bad)}
  .cards{display:none}.card,.item,.quote{border:1px solid var(--border);border-radius:13px;padding:13px}.card+.card,.item+.item{margin-top:10px}.row{display:flex;justify-content:space-between;gap:12px}.price{font-size:1.22rem;font-weight:780;margin:7px 0}.quotegrid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.list{display:grid;gap:10px}.callout{border:1px solid var(--accent);background:var(--soft);border-radius:13px;padding:13px;margin-top:12px}.progress{height:10px;border-radius:999px;background:var(--p2);overflow:hidden;margin-top:10px}.progress span{display:block;height:100%;background:var(--accent)}.empty{text-align:center;color:var(--muted);padding:20px}.nav,.install{display:none}.toast{position:fixed;z-index:50;right:18px;bottom:18px;background:var(--text);color:var(--bg);padding:11px 14px;border-radius:11px;opacity:0;transition:.2s}.toast.show{opacity:1}
  @media(max-width:960px){.metrics{grid-template-columns:repeat(2,1fr)}.grid{grid-template-columns:1fr}.controls{grid-template-columns:repeat(2,1fr)}}
  @media(max-width:680px){body{padding-bottom:calc(var(--nav) + env(safe-area-inset-bottom))}.app{width:100%;padding:14px 12px 24px}.top{align-items:center;margin-bottom:14px}.eye,.subhead,.actions .file,#export{display:none}.top h1{font-size:1.28rem}.actions button{min-height:38px;padding:7px 10px;font-size:.82rem}.metrics{display:flex;overflow-x:auto;gap:10px;margin:0 -12px 14px;padding:0 12px 3px}.metric{min-width:178px;box-shadow:none}.grid{display:block}.panel{padding:14px;box-shadow:none;margin-bottom:12px}.controls{grid-template-columns:repeat(2,1fr);gap:8px}.search{grid-column:1/-1}.table{display:none}.cards{display:block}.quotegrid{grid-template-columns:1fr}.page{display:none}.page.active{display:block}.metrics.active{display:flex}.nav{display:grid;position:fixed;z-index:40;left:0;right:0;bottom:0;grid-template-columns:repeat(4,1fr);height:calc(var(--nav) + env(safe-area-inset-bottom));padding:7px 10px calc(7px + env(safe-area-inset-bottom));background:color-mix(in srgb,var(--panel) 92%,transparent);border-top:1px solid var(--border);backdrop-filter:blur(18px)}.nav button{border:0;background:transparent;color:var(--muted);display:flex;flex-direction:column;align-items:center;justify-content:center;gap:3px;padding:4px}.nav button b{font-size:.7rem}.nav button.on{color:var(--accent)}.install{position:fixed;z-index:45;left:12px;right:12px;bottom:calc(var(--nav) + env(safe-area-inset-bottom) + 10px);display:flex;justify-content:space-between;align-items:center;padding:12px;border:1px solid var(--border);border-radius:15px;background:var(--panel)}.install[hidden]{display:none}.toast{left:12px;right:12px;bottom:calc(var(--nav) + env(safe-area-inset-bottom) + 12px);text-align:center}}
  `;
  const style = document.createElement('style'); style.textContent = css; document.head.appendChild(style);

  document.body.innerHTML = `
  <div class="app">
    <header class="top"><div><p class="eye">2027 毕业装机计划</p><h1>PC 硬件采购仪表盘</h1><p class="subhead">以人民币到手价比较日本与中国渠道，持续跟踪新品、汇率和保修风险。</p></div><div class="actions"><button id="theme">深浅色</button><label class="file">导入数据<input id="import" type="file" accept="application/json"></label><button id="export">导出数据</button></div></header>
    <section class="metrics page" data-view="home"><article class="metric"><div class="label">日元 → 人民币</div><div class="value" id="fx">—</div><div class="hint" id="fxdate">—</div></article><article class="metric"><div class="label">跟踪产品</div><div class="value" id="pcnt">—</div><div class="hint" id="newcnt">—</div></article><article class="metric"><div class="label">已验证报价</div><div class="value" id="qcnt">—</div><div class="hint" id="fresh">—</div></article><article class="metric"><div class="label">计划购买时间</div><div class="value">2027年3–4月</div><div class="hint">每月扫描新品并更新价格</div></article></section>
    <main class="grid"><div>
      <section class="panel page" data-view="products"><div class="head"><div><p class="kick">候选库</p><h2>动态候选产品</h2></div><span class="pill" id="results">0 款</span></div><div class="controls"><label class="control search">搜索<input id="search" placeholder="型号、品牌、标签…"></label><label class="control">类别<select id="category"></select></label><label class="control">状态<select id="status"><option value="all">全部</option><option value="new">新品</option><option value="active">在售</option><option value="watch">观察</option><option value="retired">退市</option></select></label><label class="control">排序<select id="sort"><option value="fit">适配评分</option><option value="price">最低已验证价</option><option value="new">最新发布</option></select></label></div><div class="table"><table><thead><tr><th>候选产品</th><th>适配度</th><th>最低已验证价</th><th>推荐渠道</th><th>配置单</th></tr></thead><tbody id="rows"></tbody></table></div><div class="cards" id="cards"></div></section>
      <section class="panel page" data-view="quotes"><div class="head"><div><p class="kick">实时报价</p><h2>已验证零售报价</h2></div><span class="pill warn">未核实价格保持为空</span></div><div class="quotegrid" id="quotes"></div></section>
      <section class="panel page" data-view="home"><div class="head"><div><p class="kick">市场雷达</p><h2>新品与市场动态</h2></div></div><div class="list" id="events"></div></section>
    </div><aside>
      <section class="panel page" data-view="build"><h2>方案设置</h2><label class="control">整机预算（人民币）<input id="budget" type="range" min="8000" max="30000" step="500"></label><div class="price" id="budgetv"></div><label class="control">手动汇率：1 日元兑换人民币<input id="fxo" type="number" step="0.000001"></label><div class="progress"><span id="bar"></span></div><p class="small" id="summary"></p><button id="clear">清空配置单</button><div class="callout"><strong id="decision"></strong><div id="decisiontext"></div></div></section>
      <section class="panel page" data-view="build"><div class="head"><h2>已选配置单</h2><span class="pill" id="bcnt">0 项</span></div><div class="list" id="basket"></div></section>
      <section class="panel page" data-view="home"><h2>采购规则</h2><div class="list" id="rules"></div></section>
      <section class="panel page" data-view="home"><h2>数据状态</h2><div class="list" id="datastatus"></div></section>
    </aside></main>
  </div>
  <div class="install" id="install" hidden><div><strong>像 App 一样使用</strong><div class="small">Safari：分享 → 添加到主屏幕</div></div><button id="dismiss">×</button></div>
  <nav class="nav"><button data-view="home" class="on">⌂<b>概览</b></button><button data-view="products">▦<b>产品</b></button><button data-view="quotes">¥<b>报价</b></button><button data-view="build">✓<b>配置</b></button></nav><div class="toast" id="toast"></div>`;

  const D = window.PC_PROCUREMENT_DATA;
  const $ = id => document.getElementById(id);
  const S = {get:k=>{try{return localStorage.getItem(k)}catch{return null}},set:(k,v)=>{try{localStorage.setItem(k,String(v))}catch{}},del:k=>{try{localStorage.removeItem(k)}catch{}}};
  let data=D,basket=new Set(JSON.parse(S.get('pc-basket')||'[]')),budget=Number(S.get('pc-budget')||D.market.profile.defaultBudgetCNY||15000),fxo=Number(S.get('pc-fx')||0),view=S.get('pc-view')||'home';
  const CL={Japan:'日本',China:'中国'},CAT={CPU:'CPU',GPU:'GPU',Motherboard:'主板',Memory:'内存',SSD:'SSD',PSU:'电源',Cooler:'散热器',Case:'机箱'},ST={new:'新品',active:'在售',watch:'观察',retired:'退市'};
  const T={'Compare landed cost, not sticker price':'比较到手价，而不是标价','Discover products before repricing':'先发现新品，再更新价格','Weight warranty by failure impact':'根据故障影响权衡保修价值','Missing price is not zero':'缺失价格不等于零元'};
  const products=()=>data.catalog.products||[],snap=()=>[...(data.snapshots.snapshots||[])].sort((a,b)=>b.date.localeCompare(a.date))[0],quotes=()=>snap()?.quotes||[],fx=()=>fxo||snap()?.fx?.JPY_CNY||0,pid=id=>products().find(p=>p.id===id),lp=q=>Number(q.checkoutPrice||0)+Number(q.shipping||0),cny=n=>new Intl.NumberFormat('zh-CN',{style:'currency',currency:'CNY',maximumFractionDigits:0}).format(n||0),toc=q=>q.currency==='JPY'?lp(q)*fx():lp(q),best=id=>quotes().filter(q=>q.productId===id).sort((a,b)=>toc(a)-toc(b))[0]||null,esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function toast(t){$('toast').textContent=t;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),1800)}
  function advice(p,q){if((p.tags||[]).includes('buy-in-japan'))return'日本——保修与物流更方便';if((p.tags||[]).includes('china-value'))return'中国——优先核实官方旗舰店';return q?`${CL[q.country]||q.country}——当前已验证价格更低`:'等待中日两地报价'}
  function filtered(){let term=$('search').value.toLowerCase(),cat=$('category').value,st=$('status').value,a=products().filter(p=>(!term||[p.model,p.brand,p.category,p.platform,...(p.tags||[])].join(' ').toLowerCase().includes(term))&&(cat==='all'||p.category===cat)&&(st==='all'||p.status===st));let sort=$('sort').value;a.sort((x,y)=>sort==='price'?(best(x.id)?toc(best(x.id)):1e20)-(best(y.id)?toc(best(y.id)):1e20):sort==='new'?(y.releaseDate||'').localeCompare(x.releaseDate||''):y.fitScore-x.fitScore);return a}
  function renderProducts(){let a=filtered();$('results').textContent=`${a.length} 款`;$('rows').innerHTML=a.map(p=>{let q=best(p.id);return`<tr><td><div class="model">${esc(p.brand)} ${esc(p.model)}</div><div class="small">${esc(p.specSummary)}</div><span class="pill">${ST[p.status]||p.status}</span></td><td><b class="good">${p.fitScore}/100</b><div class="small">${esc(p.fitReason)}</div></td><td>${q?cny(toc(q)):'暂无报价'}</td><td>${advice(p,q)}</td><td><button class="pick" data-id="${p.id}">${basket.has(p.id)?'移除':'加入'}</button></td></tr>`}).join('')||'<tr><td colspan="5" class="empty">没有符合条件的产品</td></tr>';$('cards').innerHTML=a.map(p=>{let q=best(p.id);return`<article class="card"><div class="row"><div><div class="model">${esc(p.brand)} ${esc(p.model)}</div><div class="small">${esc(p.specSummary)}</div></div><b class="good">${p.fitScore}</b></div><span class="pill">${ST[p.status]||p.status}</span><div class="row" style="margin-top:12px"><div><div class="price">${q?cny(toc(q)):'暂无报价'}</div><div class="small">${advice(p,q)}</div></div><button class="pick" data-id="${p.id}">${basket.has(p.id)?'移除':'加入'}</button></div></article>`}).join('');document.querySelectorAll('.pick').forEach(b=>b.onclick=()=>toggle(b.dataset.id))}
  function renderQuotes(){$('quotes').innerHTML=[...quotes()].sort((a,b)=>toc(a)-toc(b)).map(q=>{let p=pid(q.productId),age=Math.max(0,Math.floor((Date.now()-new Date(q.verifiedAt))/86400000));return`<article class="quote"><div class="row"><b lang="${q.country==='Japan'?'ja':'zh-CN'}">${esc(q.listingTitle||p?.model||q.productId)}</b><span class="pill">${age} 天前</span></div><div class="price">${cny(toc(q))}</div><div>${CL[q.country]||q.country} · ${esc(q.platform)}</div><div class="small">${q.currency} ${lp(q).toLocaleString()} · <a href="${esc(q.sourceUrl)}" target="_blank">查看来源</a></div></article>`}).join('')||'<div class="empty">暂无已验证报价</div>'}
  function renderEvents(){$('events').innerHTML=[...(data.events.events||[])].sort((a,b)=>b.date.localeCompare(a.date)).map(e=>`<article class="item"><div class="row"><b>${esc(e.title)}</b><span class="pill ${e.type==='market-risk'?'warn':'good'}">${e.type==='market-risk'?'市场风险':'新品'}</span></div><div class="small">${e.date}</div><div class="small">${esc(e.detail)}</div></article>`).join('')}
  function renderRules(){$('rules').innerHTML=(data.market.rules||[]).map(r=>`<article class="item"><b>${T[r.title]||esc(r.title)}</b><div class="small">${esc(r.detail)}</div></article>`).join('')}
  function renderMetrics(){let s=snap(),ages=quotes().map(q=>Math.max(0,Math.floor((Date.now()-new Date(q.verifiedAt))/86400000)));$('fx').textContent=fx().toFixed(6);$('fxdate').textContent=s?`${s.fx.source} · ${s.date}`:'暂无数据';$('pcnt').textContent=products().length;$('newcnt').textContent=`其中 ${products().filter(p=>p.status==='new').length} 款新品`;$('qcnt').textContent=quotes().length;$('fresh').textContent=ages.length?`最新报价 ${Math.min(...ages)} 天前`:'暂无报价'}
  function renderBasket(){let chosen=[...basket].map(pid).filter(Boolean),known=chosen.map(p=>({p,q:best(p.id)})).filter(x=>x.q),total=known.reduce((s,x)=>s+toc(x.q),0),miss=chosen.length-known.length;$('budget').value=budget;$('budgetv').textContent=cny(budget);$('fxo').value=fx();$('bar').style.width=`${Math.min(100,total/budget*100)}%`;$('summary').textContent=chosen.length?`${cny(total)} 已验证小计 · ${miss} 个缺价`:'尚未选择配件';$('bcnt').textContent=`${chosen.length} 项`;$('basket').innerHTML=chosen.map(p=>{let q=best(p.id);return`<article class="item"><div class="row"><b>${CAT[p.category]||p.category}: ${esc(p.model)}</b><span>${q?cny(toc(q)):'暂无价格'}</span></div><div class="small">${q?`${CL[q.country]||q.country} · ${esc(q.platform)}`:'需要补充中日报价'}</div></article>`}).join('')||'<div class="empty">请从产品页加入配件</div>';$('decision').textContent=miss?'配置单价格不完整':total>budget?'超出预算':'当前决策建议';$('decisiontext').textContent=miss?'先补齐缺失的价格依据。':total>budget?'下调 CPU/GPU 档位或等待更好价格。':'现在先确定平台，接近购买时再锁定型号。'}
  function renderStatus(){$('datastatus').innerHTML=`<article class="item"><div class="row"><b>最新数据快照</b><span>${snap()?.date||'—'}</span></div></article><article class="item"><div class="row"><b>已有报价的产品</b><span>${new Set(quotes().map(q=>q.productId)).size}/${products().length}</span></div></article>`}
  function render(){renderMetrics();renderProducts();renderQuotes();renderEvents();renderRules();renderBasket();renderStatus()}
  function toggle(id){basket.has(id)?basket.delete(id):basket.add(id);S.set('pc-basket',JSON.stringify([...basket]));renderProducts();renderBasket()}
  function setView(v){view=v;S.set('pc-view',v);document.querySelectorAll('.nav button').forEach(b=>b.classList.toggle('on',b.dataset.view===v));document.querySelectorAll('.page').forEach(p=>p.classList.toggle('active',p.dataset.view===v));if(matchMedia('(max-width:680px)').matches)scrollTo({top:0,behavior:'smooth'})}
  $('category').innerHTML='<option value="all">全部</option>'+[...new Set(products().map(p=>p.category))].map(c=>`<option value="${c}">${CAT[c]||c}</option>`).join('');
  ['search','category','status','sort'].forEach(id=>$(id).addEventListener(id==='search'?'input':'change',renderProducts));$('budget').oninput=e=>{budget=Number(e.target.value);S.set('pc-budget',budget);renderBasket()};$('fxo').onchange=e=>{fxo=Number(e.target.value);S.set('pc-fx',fxo);render()};$('clear').onclick=()=>{basket.clear();S.del('pc-basket');renderProducts();renderBasket()};$('theme').onclick=()=>{let n=document.documentElement.dataset.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=n;S.set('pc-theme',n)};$('export').onclick=()=>{let u=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=u;a.download='pc-procurement.json';a.click();URL.revokeObjectURL(u)};$('import').onchange=async e=>{try{let x=JSON.parse(await e.target.files[0].text());data=x;render();toast('数据已导入')}catch{toast('数据格式无效')}};document.querySelectorAll('.nav button').forEach(b=>b.onclick=()=>setView(b.dataset.view));$('dismiss').onclick=()=>{$('install').hidden=true;S.set('pc-install','off')};
  document.documentElement.dataset.theme=S.get('pc-theme')||(matchMedia('(prefers-color-scheme:dark)').matches?'dark':'light');render();setView(view);if(/iphone|ipad|ipod/i.test(navigator.userAgent)&&navigator.standalone!==true&&S.get('pc-install')!=='off')$('install').hidden=false;
})();
